version: '2.1'

volumes:
  pgdata:
  walletstore:

networks:
  nb-samlinux:

services:

  explorerdb.nb-samlinux.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.nb-samlinux.com
    hostname: explorerdb.nb-samlinux.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nb-samlinux

  explorer.nb-samlinux.com:
    image: hyperledger/explorer:latest
    container_name: explorer.nb-samlinux.com
    hostname: explorer.nb-samlinux.com
    environment:
      - DATABASE_HOST=explorerdb.nb-samlinux.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./explorer-config.json:/opt/explorer/app/platform/fabric/config.json
      - ./connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ./crypto-config:/tmp/crypto
      - walletstore:/opt/explorer/wallet
    ports:
      - 8080:8080
    depends_on:
      explorerdb.nb-samlinux.com:
        condition: service_healthy
    networks:
      - nb-samlinux